CREATE TABLE bookstore.AUTHOR
(
  ID_AUTHOR   int8          NOT NULL,
  FIRST_NAME  varchar(100) NOT NULL,
  LAST_NAME   varchar(100) NOT NULL,
  DESCRIPTION text         NOT NULL,
  CONSTRAINT pk_AUTHOR PRIMARY KEY (ID_AUTHOR)
);
CREATE INDEX in_author_first_name on bookstore.AUTHOR USING btree(FIRST_NAME);
CREATE INDEX in_author_last_name ON  bookstore.AUTHOR USING btree(LAST_NAME);

CREATE TABLE bookstore.BOOK_AUTHOR
(
  ID_BOOK_AUTHOR int8 NOT NULL,
  ID_AUTHOR      int8 NOT NULL,
  ID_BOOK        int8 NOT NULL,
  CONSTRAINT pk_BOOK_AUTHOR PRIMARY KEY ( ID_BOOK_AUTHOR )
);

ALTER TABLE bookstore.BOOK_AUTHOR
  ADD CONSTRAINT fk_BOOK_AUTHOR_ID_AUTHOR FOREIGN KEY (ID_AUTHOR)
    REFERENCES bookstore.AUTHOR (ID_AUTHOR);

ALTER TABLE bookstore.BOOK_AUTHOR
  ADD CONSTRAINT fk_BOOK_AUTHOR_ID_BOOK FOREIGN KEY (ID_BOOK)
    REFERENCES bookstore.BOOK (ID_BOOK);

CREATE SEQUENCE bookstore.S_AUTHOR INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE bookstore.S_BOOK_AUTHOR INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1;